#!/usr/bin/env php
<?php

/*
 * This file is part of the "EloGank League of Legends Replay Downloader" package.
 *
 * https://github.com/EloGank/lol-replay-downloader
 *
 * For the full license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require 'vendor/autoload.php';

$application = new Symfony\Component\Console\Application();

// List all available commands
$iterator = new \GlobIterator(__DIR__ . '/src/EloGank/Replay/Command/*Command.php');
/** @var \SplFileInfo $command */
foreach ($iterator as $command) {
    if ($command->isDir()) {
        continue;
    }

    $namespace = '\\EloGank\\Replay\\Command\\' . substr($command->getFilename(), 0, -4);
    $reflectionClass = new \ReflectionClass($namespace);

    if ($reflectionClass->isSubclassOf('\\EloGank\\Component\\Command\\Command')) {
        $application->add(new $namespace());
    }
}

$application->run();